import { ThemeName, ThemeColors } from '../types';

export const THEMES: Record<ThemeName, ThemeColors> = {
  stitch_light: {
    name: 'Stitch Light Dashboard',
    bg: 'bg-[#f8fafc] text-slate-900',
    card: 'bg-white border border-slate-200/90 shadow-[0_1px_3px_rgba(0,0,0,0.04)] rounded-xl',
    border: 'border-slate-200',
    primary: 'bg-slate-900 hover:bg-slate-800 text-white shadow-sm font-semibold tracking-tight transition-all duration-200 rounded-lg',
    primaryHover: 'hover:bg-slate-800',
    text: 'text-slate-900',
    textMuted: 'text-slate-500',
    accent: 'text-indigo-600',
    accentBg: 'bg-indigo-50 border border-indigo-200 text-indigo-800',
    badgeGreen: 'bg-emerald-50 border border-emerald-200/80 text-emerald-800 rounded-md font-mono text-[9px] font-medium',
    badgeYellow: 'bg-amber-50 border border-amber-200/80 text-amber-800 rounded-md font-mono text-[9px] font-medium',
    badgeRed: 'bg-rose-50 border border-rose-200/80 text-rose-800 rounded-md font-mono text-[9px] font-medium',
    badgeBlue: 'bg-sky-50 border border-sky-200/80 text-sky-800 rounded-md font-mono text-[9px] font-medium',
    neonShadow: 'shadow-sm',
    fontDisplay: 'font-sans',
    fontSans: 'font-sans'
  },
  stitch_dark: {
    name: 'Stitch Dark Dashboard',
    bg: 'bg-[#0f172a] text-slate-100',
    card: 'bg-[#1e293b]/95 border border-slate-800 shadow-md rounded-xl',
    border: 'border-slate-800',
    primary: 'bg-slate-100 hover:bg-white text-slate-950 shadow-sm font-semibold tracking-tight transition-all duration-200 rounded-lg',
    primaryHover: 'hover:bg-white',
    text: 'text-slate-100',
    textMuted: 'text-slate-400',
    accent: 'text-slate-200',
    accentBg: 'bg-slate-800 border border-slate-700 text-slate-200',
    badgeGreen: 'bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded-md font-mono text-[9px] font-medium',
    badgeYellow: 'bg-amber-500/10 border border-amber-500/20 text-amber-300 rounded-md font-mono text-[9px] font-medium',
    badgeRed: 'bg-rose-500/10 border border-rose-500/20 text-rose-400 rounded-md font-mono text-[9px] font-medium',
    badgeBlue: 'bg-sky-500/10 border border-sky-500/20 text-sky-300 rounded-md font-mono text-[9px] font-medium',
    neonShadow: 'shadow-md',
    fontDisplay: 'font-sans',
    fontSans: 'font-sans'
  },
  backstage_neon: {
    name: 'Executive Studio (Gold & Charcoal)',
    bg: 'bg-[#0e0e11] text-[#e4e4e7]',
    card: 'bg-[#16161a]/95 border border-neutral-800 shadow-sm rounded-xl',
    border: 'border-neutral-800',
    primary: 'bg-zinc-100 hover:bg-white text-zinc-950 shadow-sm font-semibold tracking-tight transition-all duration-200 rounded-lg',
    primaryHover: 'hover:bg-white',
    text: 'text-[#e4e4e7]',
    textMuted: 'text-neutral-400',
    accent: 'text-amber-300/90',
    accentBg: 'bg-neutral-800/80 border border-neutral-700/60 text-zinc-200',
    badgeGreen: 'bg-emerald-500/10 border border-emerald-500/20 text-emerald-400/90 rounded-md font-mono text-[9px] font-medium',
    badgeYellow: 'bg-amber-500/10 border border-amber-500/20 text-amber-300/90 rounded-md font-mono text-[9px] font-medium',
    badgeRed: 'bg-rose-500/10 border border-rose-500/20 text-rose-300/90 rounded-md font-mono text-[9px] font-medium',
    badgeBlue: 'bg-indigo-500/10 border border-indigo-500/20 text-indigo-300/90 rounded-md font-mono text-[9px] font-medium',
    neonShadow: 'shadow-sm',
    fontDisplay: 'font-display',
    fontSans: 'font-sans'
  },
  roots_ska: {
    name: 'Obsidian Studio (Dark Monochrome)',
    bg: 'bg-[#09090b] text-[#f4f4f5]',
    card: 'bg-[#121215]/95 border border-neutral-800/90 shadow-sm rounded-xl',
    border: 'border-neutral-800/80',
    primary: 'bg-zinc-100 hover:bg-white text-zinc-950 shadow-sm font-semibold tracking-tight transition-all duration-200 rounded-lg',
    primaryHover: 'hover:bg-white',
    text: 'text-zinc-100',
    textMuted: 'text-zinc-400',
    accent: 'text-zinc-200',
    accentBg: 'bg-zinc-800/80 border border-zinc-700/60 text-zinc-200',
    badgeGreen: 'bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded-md font-mono text-[9px] font-medium',
    badgeYellow: 'bg-amber-500/10 border border-amber-500/20 text-amber-300 rounded-md font-mono text-[9px] font-medium',
    badgeRed: 'bg-rose-500/10 border border-rose-500/20 text-rose-300 rounded-md font-mono text-[9px] font-medium',
    badgeBlue: 'bg-sky-500/10 border border-sky-500/20 text-sky-300 rounded-md font-mono text-[9px] font-medium',
    neonShadow: 'shadow-sm',
    fontDisplay: 'font-sans',
    fontSans: 'font-sans'
  },
  indie_velvet: {
    name: 'Studio Graphite (Sleek Warm Dark)',
    bg: 'bg-[#121110] text-[#e5e2e1]',
    card: 'bg-[#1a1918] border border-neutral-800/80 shadow-sm rounded-xl',
    border: 'border-neutral-800/80',
    primary: 'bg-[#eab308] hover:bg-[#facc15] text-[#121110] font-bold tracking-tight transition-all duration-200 rounded-lg',
    primaryHover: 'hover:bg-[#facc15]',
    text: 'text-[#e5e2e1]',
    textMuted: 'text-[#9a9591]',
    accent: 'text-[#eab308]',
    accentBg: 'bg-[#22211f] text-[#e5e2e1]',
    badgeGreen: 'bg-[#4a5d23]/20 text-[#86a760] rounded-md font-mono text-[9px] font-bold uppercase tracking-wider',
    badgeYellow: 'bg-[#7a591a]/20 text-[#d8a032] rounded-md font-mono text-[9px] font-bold uppercase tracking-wider',
    badgeRed: 'bg-[#6b2c2c]/20 text-[#c76565] rounded-md font-mono text-[9px] font-bold uppercase tracking-wider',
    badgeBlue: 'bg-[#2c4a6b]/20 text-[#6592c7] rounded-md font-mono text-[9px] font-bold uppercase tracking-wider',
    neonShadow: 'shadow-none',
    fontDisplay: 'font-display',
    fontSans: 'font-sans'
  },
  brutalist_fuzz: {
    name: 'Minimal Mono (Tech Clean)',
    bg: 'bg-[#0d0d0e] text-[#f4f4f5]',
    card: 'bg-[#141416]/95 border border-neutral-800 shadow-sm rounded-xl',
    border: 'border-neutral-800',
    primary: 'bg-zinc-100 hover:bg-white text-zinc-950 shadow-sm font-semibold tracking-tight transition-all duration-200 rounded-lg',
    primaryHover: 'hover:bg-white',
    text: 'text-zinc-100',
    textMuted: 'text-zinc-400',
    accent: 'text-zinc-200',
    accentBg: 'bg-zinc-800/80 border border-zinc-700/60 text-zinc-200',
    badgeGreen: 'bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded-md font-mono text-[9px] font-medium',
    badgeYellow: 'bg-amber-500/10 border border-amber-500/20 text-amber-300 rounded-md font-mono text-[9px] font-medium',
    badgeRed: 'bg-rose-500/10 border border-rose-500/20 text-rose-300 rounded-md font-mono text-[9px] font-medium',
    badgeBlue: 'bg-sky-500/10 border border-sky-500/20 text-sky-300 rounded-md font-mono text-[9px] font-medium',
    neonShadow: 'shadow-sm',
    fontDisplay: 'font-mono',
    fontSans: 'font-mono'
  }
};
